import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './context/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': 'var(--color-surface-bright)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'error': 'var(--color-error)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'surface': 'var(--color-surface)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'on-error-container': 'var(--color-on-error-container)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'on-secondary': 'var(--color-on-secondary)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'surface-container': 'var(--color-surface-container)',
        'on-error': 'var(--color-on-error)',
        'tertiary': 'var(--color-tertiary)',
        'on-background': 'var(--color-on-background)',
        'on-surface': 'var(--color-on-surface)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'primary': 'var(--color-primary)',
        'outline': 'var(--color-outline)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'surface-variant': 'var(--color-surface-variant)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'secondary': 'var(--color-secondary)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'background': 'var(--color-background)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'outline-variant': 'var(--color-outline-variant)',
        'error-container': 'var(--color-error-container)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-primary': 'var(--color-on-primary)',
        'surface-tint': 'var(--color-surface-tint)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'surface-dim': 'var(--color-surface-dim)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'secondary-container': 'var(--color-secondary-container)',
        'primary-container': 'var(--color-primary-container)',
        'secondary-dim': 'var(--color-secondary-dim)',
        'primary-dim': 'var(--color-primary-dim)',
        'error-dim': 'var(--color-error-dim)',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
    },
  },
  plugins: [],
}

export default config;
